### ISSUE TITLE
Colorama compatibility

### ISSUE THREAD

**Issue by thorstenkampe** [Drekin/win-unicode-console#11]
The readme claims "win_unicode_console package [...] interacts well with [...] colorama package[s]". The following code snippet shows that the output changes depending on whether you first call `win_unicode_console.enable()` or `colorama.init()` (see screenshot). `progress` and `test_progress` are from here: https://github.com/verigak/progress.

In the first case, ansi escape sequences are displayed (win_unicode_console.enable "overrides" colorama. In the second case, unicode characters are displayed as "\u" (colorama overrides win_unicode_console.enable)

```
import colorama, win_unicode_console

colorama.init()
win_unicode_console.enable()

import progress, test_progress
```
![27-03-_2015_15-00-44](https://cloud.githubusercontent.com/assets/475462/6869201/9fe8cd20-d492-11e4-9ce7-d8089c3e5442.png)

**Comment by Drekin** [comment]
`win_unicode_console.enable()` has to be done first, since it doesn't wrap anything. It creates new streams and the original ones are replaced. Colorama wraps any present stream and filters out and interprets the ANSI control sequences.

The problem here is early binding behavior of `progress`, which stores the stderr stream at import time, so it doesn't consider the stream object might change. First calling `win_unicode_console.enable()`, then `colorama.init()`, and then importing `progress` should work.

**Comment by thorstenkampe** [comment]
If I call `colorama.init()` last, it will show all the `\u` escapes as shown in my screenshot...

**Comment by Drekin** [comment]
Not if the package `progress` wasn't imported before. You can always try `sys.stdout.write("\x1b[K")` interactively to see what's happening.

**Comment by Drekin** [comment]
I've opened the referenced issue for `progress` package. I've also added documentation how to use `win_unicode_console` with `colorama` or some other packages.
