### ISSUE TITLE
Unicode sys.argv on python 2

### ISSUE THREAD

**Issue by ololoe** [Drekin/win-unicode-console#20]
Don't you want to take this http://stackoverflow.com/a/846931 into a pypi module? If yes, patch __ file __ too.

**Comment by Drekin** [comment]
Maybe if there's some time… Are you sure such pypi module doesn't already exist?

**Comment by ololoe** [comment]
Never saw it. Pypi module would allow this code to be availiable from every program without being copypasted, or is there any method with comparable handiness including moving your code to other computer?

**Comment by anthrotype** [comment]
👍

**Comment by Drekin** [comment]
Actually it seems that `win_unicode_console` itself would benefit from this – scripts with non-ASCII filenames could be run by the runner, e.g. `py -2 -m run α.py` would work.

**Comment by Drekin** [comment]
Currently, I'm struggling with auto-enabling the Unicode argv since `sys.argv` is not populated yet during the execution of `sitecustomize`. Any ideas?

**Comment by anthrotype** [comment]
Yeah, I also stumbled on the same issue the last time I tried... :(

**Comment by anthrotype** [comment]
it's weird..

the `PySys_SetArgv` function, which is defined in the [sysmodule.c#l1723](https://hg.python.org/releases/2.7.11/file/2.7/Python/sysmodule.c#l1723), is used in `Modules/main.c`:

https://hg.python.org/releases/2.7.11/file/2.7/Modules/main.c#l581

I presume this happens before `sitecustomize.py` is imported and executed by `site.py`, no?

**Comment by Drekin** [comment]
Unfortunately not, `site.py` is imported in `Py_Initialize` (https://hg.python.org/cpython/file/2.7/Python/pythonrun.c#l284), which is called before `PySys_SetArgv`.

**Comment by anthrotype** [comment]
oh nooo! :(

what if we try using `Py_GetArgcArgv` from `sysmodule.c`? That should retrieve the "original" argc and argv...

**Comment by Drekin** [comment]
That would give us the raw unprocessed argv with all the options given to `python.exe`.

I was thinking about something like temporarily altering `sys.modules['sys']` to a wrapper waiting for `sys.argv` being set.

**Comment by anthrotype** [comment]
hmm, sounds dangerous! but let's try that :)

**Comment by anthrotype** [comment]
a less elegant solution could be to simply expose them as `win_unicode_console.argv` instead of replacing `sys.argv` directly. Then if one wants the unicode argv strings, it could simply get them from there?

**Comment by anthrotype** [comment]
Since we are talking about Unicode sys.argv, I think it's worth mentioning that the Windows *.exe launchers which setuptools generates for `console_scripts` and `gui_scripts` entry_points when installing a package from source, _do not support Unicode command line arguments_ -- not even on Python 3.

This is because the setuptools launchers do not use the Windows Unicode API to retrieve the command line arguments from the console. As a result the python script only sees "?" for those characters which can't be encoded in the current codepage.
Using ctypes won't help here, since the launchers have already messed up the original arguments by the time we try to access them.

Nevertheless, there is also a new kind of Windows launchers that pip uses, but only when installing a package from a wheel. These launchers, which come from a vendored library called [distlib](https://bitbucket.org/pypa/distlib), do support Unicode arguments; and unlike setuptools', they are self-contained (ie. the wrapped script content is zipped in the executables, whereas with setuptools theee is an external "*-script.py" in the same folder as the *.exe).

I'm working on a PR to make setuptools to use the distlib launchers.
https://github.com/pypa/setuptools/pull/595

Until this lands, we should keep in mind that the unicode argv ctypes workaround won't work when running python scripts via the setuptools wrappers.

**Comment by Drekin** [comment]
Hmm, interesting. So even when ctypes call WinAPI function `GetCommandLineW` the argv is messed?

Also, `PySys_SetArgv` doesn't invoke any hook like retrieving `sys` from `sys.modules` or `__setitem__` of `sys.__dict__`, so currently I see no place to hook up.

**Comment by anthrotype** [comment]
yeah, `GetCommandLineW` is ineffective because the command line arguments that are passed from the console to the launcher are channelled through the "narrow" `main(int argc, char **argv)`, instead of the "wide" (Windows specific) `wmain` entry point.

The distlib launchers use the same `GetCommandLineW` to access the arguments, before passing them to the wrapped script. The `argv` from `main` are discarded (I think they didn't use `wmain` because some mingw version didn't support it).

**Comment by Drekin** [comment]
I got a hint to use `sys.path_hooks` to get the desired behavior (see https://mail.python.org/pipermail/python-list/2016-June/710183.html). So I have automatic Unicode argv now. But breaks `pip` because of https://hg.python.org/cpython/file/2.7/Lib/distutils/cmd.py#l214. :-(

**Comment by anthrotype** [comment]
that's very clever! 
that's a pity though.. I guess distutils won't be the only one making the assumption that sys.argv should be byte strings on Python 2. :-/

But wait... What if we encode the sys.argv as UTF-8 on python 2?
After all, win_unicode_console is already enforcing that as default stdin/stdout encoding, so it would make sense to also have argv as UTF-8 bytes on Python 2 (like it's the case on most Unix systems).

**Comment by Drekin** [comment]
Well, the UTF-8 encoding on `sys.std*` objects is just kind of fallback when somebody passes bytes. We should use Unicode strings all the time. But more serious problem is that you cannot open a UTF-8 encoded path (unless it is ASCII).

**Comment by Drekin** [comment]
There is even 2.5 years old issue regarding this: https://bugs.python.org/issue19570.

For now, I have commited the code to the Deveopment branch. Unicode `sys.argv` is not set by default, but you can use `win_unicode_console.enable(use_unicode_argv=True)`.

**Comment by anthrotype** [comment]
Thanks!

**Comment by ololoe** [comment]
You should mention that this won't work if something else substitutes sys.argv, for example IDEs' option "set command line parameters"
