### ISSUE TITLE
Package is not compatible with Python2

### ISSUE THREAD

**Issue by thorstenkampe** [Drekin/win-unicode-console#7]
If the package doesn't support Python2, that should be stated

```
thorsten@rednails[F:\...\script] tcc> python2 script.py
Traceback (most recent call last):
  File "script.py", line 17, in <module>
    import win_unicode_console
  File "F:\PortableApps\Python2x\lib\site-packages\win_unicode_console\__init__.py", line 7
    def enable(*,
                ^
SyntaxError: invalid syntax
```

**Comment by Drekin** [comment]
Python 2 is currently not supported, because the main concerns of the package are Unicode, IO, and Python internals, all of which was extensively overhauled in Python 3. Once I tried to add Python 2 support, but then I realized how much is Python 2 different. Maybe I'll give it another try.

What do you think is a proper way to declare that Python 2 is not supported? A note in package overview? Or even something like http://stackoverflow.com/questions/26437467/is-there-a-standard-way-to-declare-old-python-versions-unsupported? Currently, only Python 3 versions are present in setup.py classifiers.

**Comment by thorstenkampe** [comment]
First, there are categories on PyPi. `Programming Language :: Python :: 3 :: Only` seems to be the correct one for your package. And `Operating System :: Microsoft :: Windows`, of course. 

But being multi-platform (without actually doing anything on Linux and OS X like Colorama) would be better.

You can use classifier in setup.py, too: https://pythonhosted.org/an_example_pypi_project/setuptools.html#classifiers

Or you build a wheel package, they are (or can be) version dependent, as far as I know.

**Comment by Drekin** [comment]
Thank you, I didn't know about the `:: Only` variant of the classifier. If I don't add support for Python 2, I'll add that classifier.

Can you please repost the other part of your comment to the relevant issue?

**Comment by Drekin** [comment]
Python 2 is now supported.
